### ISSUE TITLE
MOV EBP causes a 'memory address out of range' exception

### ISSUE THREAD

**Issue by mathiasj33** [TUM-LRR/Jasmin#26]
The simple assembly program

`call fn
jmp end

fn:
mov ebp,esp
ret

end:`

causes a 'memory address out of range' exception. Replacing ebp with any other register such as eax does not lead to this error.

**Comment by meyerm** [comment]
Jasmin has some internal logic checks that validate the usage of ESP/EBP as learned in the lecture. So EBP can never be above (smaller) than ESP. If you do not PUSH and later POP EBP, you'd end up with EBP at 4092 and ESP at 4096 which Jasmin refuses as error. In pure assembler you could ignore these convention, though.
