### ISSUE TITLE
64bit support?

### ISSUE THREAD

**Issue by dodona2** [TUM-LRR/Jasmin#46]
jasmin doesn't know the 16 registers of a amd64 cpu. However 64bit chips are standard today.

**Comment by meyerm** [comment]
While it is totally true that today effectively all new x86-setups are 64 bit, Jasmin's goal is to provide an easy to play around with environment for the first steps of the students. Supporting 64 bit wouldn't improve that. That doesn't mean we wouldn't accept patches - but the afford needed to switch Jasmin to 64 bit is not a small one.

Please have a look at our other simulator project (currently called erasim). It's flexible from the ground up and far easier to extend. Stabilising that would surely be more beneficial for everybody than trying to rewrite huge parts of Jasmin.
