### ISSUE TITLE
Breakpoints ? 

### ISSUE THREAD

**Issue by rasaford** [TUM-LRR/Jasmin#47]
What do you guys think about adding breakpoints to Jasmin ? I am thinking of something very similar in functionality to the ones in Intellij or VsCode. It would definitely make debugging any moderately complex code a lot easier and more user friendly. 
As far as I understand the application right now it also shouldn't bee to hard to implement as we already have the line by line step through functionality. 

### Planned features:

- ability to visually place a breakpoint on any line
- new button to run the program until a breakpoint is hit
- the last executed line is highlighted

Let me know what you guys think. If we can reach a consensus and I get some time I am thinking of going for a first implementation and submitting a PR.

**Comment by meyerm** [comment]
Thank you for your suggestion. Did you already try to click on the sidebar left of the line numbers? :)

**Comment by meyerm** [comment]
Mh, but I agree, it's probably not intuitive to see (actually, you have to know it...). So, if you're motivated to have a look, we'd be happy to merge a PR that makes that feature more prominent. (And all the other features you'd like to hack ;) )
