### ISSUE TITLE
Pop ebp in leave does not work

### ISSUE THREAD

**Issue by findusl** [TUM-LRR/Jasmin#6]
In assembler there is the leave function that usually executes the following code: 
mov   esp, ebp
pop    ebp

However this won't work in jasmin, probably because jasmin first tries to increase esp before writing the popped value to ebp, which results in esp being bigger than ebp after the increasing which is not allowed.

Can you please fix this?

**Comment by palle-k** [comment]
This issue was already submitted [in this issue](https://github.com/TUM-LRR/Jasmin/issues/1).
The issue has been solved.

**Comment by meyerm** [comment]
True, solved in issue #1 by pull request #2.
